export default {
  type: 'admin',
  routes: [
    {
      method: 'POST',
      path: '/chat',
      handler: 'controller.chat',
      config: {
        policies: [],
        middlewares: ['plugin::ai-sdk.guardrail'],
      },
    },
    {
      method: 'GET',
      path: '/conversations',
      handler: 'conversation.find',
      config: { policies: [] },
    },
    {
      method: 'GET',
      path: '/conversations/:id',
      handler: 'conversation.findOne',
      config: { policies: [] },
    },
    {
      method: 'POST',
      path: '/conversations',
      handler: 'conversation.create',
      config: { policies: [] },
    },
    {
      method: 'PUT',
      path: '/conversations/:id',
      handler: 'conversation.update',
      config: { policies: [] },
    },
    {
      method: 'DELETE',
      path: '/conversations/:id',
      handler: 'conversation.delete',
      config: { policies: [] },
    },
    {
      method: 'GET',
      path: '/memories',
      handler: 'memory.find',
      config: { policies: [] },
    },
    {
      method: 'POST',
      path: '/memories',
      handler: 'memory.create',
      config: { policies: [] },
    },
    {
      method: 'PUT',
      path: '/memories/:id',
      handler: 'memory.update',
      config: { policies: [] },
    },
    {
      method: 'DELETE',
      path: '/memories/:id',
      handler: 'memory.delete',
      config: { policies: [] },
    },
    {
      method: 'GET',
      path: '/public-memories',
      handler: 'public-memory.find',
      config: { policies: [] },
    },
    {
      method: 'POST',
      path: '/public-memories',
      handler: 'public-memory.create',
      config: { policies: [] },
    },
    {
      method: 'PUT',
      path: '/public-memories/:id',
      handler: 'public-memory.update',
      config: { policies: [] },
    },
    {
      method: 'DELETE',
      path: '/public-memories/:id',
      handler: 'public-memory.delete',
      config: { policies: [] },
    },
    {
      method: 'GET',
      path: '/tasks',
      handler: 'task.find',
      config: { policies: [] },
    },
    {
      method: 'POST',
      path: '/tasks',
      handler: 'task.create',
      config: { policies: [] },
    },
    {
      method: 'PUT',
      path: '/tasks/:id',
      handler: 'task.update',
      config: { policies: [] },
    },
    {
      method: 'DELETE',
      path: '/tasks/:id',
      handler: 'task.delete',
      config: { policies: [] },
    },
  ],
};
